@startuml
hide methods
hide stereotypes

entity Project {
  + project_id [PK]
  --
  name VARCHAR[255]
}

entity Story {
  + story_id [PK]
  --
  project_id [FK]
  subject VARCHAR[255]
  description CLOB
  point NUMBER[2,1]
}
entity Task {
  + task_id [PK]
  --
  subject
  description
  estimated_hours
}

entity IterationPlan {
  + iteration_id [PK]
  + story_id [PK]
  --
  position INTEGER
}

entity Iteration {
  + iteration_id [PK]
  --
  subject
  description
  start_on
  end_on
}

entity DevelopmentTask {
  + task_id [PK]
  --
  + story_id
}

Project --right--{ Iteration
Project ----{ Story
Iteration ----{ IterationPlan
IterationPlan }---- Story
Project |o--right--{ Task
Task ---o| DevelopmentTask
Task ---o| Overheads
DevelopmentTask }---- Story
@enduml
