@startuml
hide methods
hide stereotypes

entity Project {
  + id [PK]
  --
  name VARCHAR[255]
}

entity Task {
  + ID [PK]
  --
  subject
  description
  estimated_hours
}

entity IterationPlan {
  + iteration_id [PK]
  + story_id [PK]
  --
  position
}

Project --right--{ Iteration
Project ----{ Story
Iteration ----{ IterationPlan
IterationPlan }---- Story
Project |o--right--{ Task
Task ---o| DevelopmentTask
Task ---o| Overheads
DevelopmentTask }---- Story
@enduml
